In [2]:
import numpy as np

In [ ]:
#collecting data 
# rows = student [AKASH,RIYA,KAJAL,PRIYA,RAHUL,MAYANK].
# column = subject[MATHS,SCIENCE,ENGLISH,HINDI,SOCIAL SCIENCE] respectively.


In [4]:
marks = np.array((
        [90,87,67,46,87],
        [98,78,33,87,88],
        [78,92,44,23,93],
        [29,99,66,59,80],
        [92,87,93,95,86],
        [39,94,63,45,82]  
))

students =["Akash","Riya","Kajal",'Priya','Rahul','Mayank']
subjects = ['Maths','Science','English','Hindi','Social science']
print(students)
print(subjects)
print(marks)

['Akash', 'Riya', 'Kajal', 'Priya', 'Rahul', 'Mayank']
['Maths', 'Science', 'English', 'Hindi', 'Social science']
[[90 87 67 46 87]
 [98 78 33 87 88]
 [78 92 44 23 93]
 [29 99 66 59 80]
 [92 87 93 95 86]
 [39 94 63 45 82]]


Student-wise averge helps to evaluate individual performance.(row wise)

In [138]:
student_average = np.mean(marks,axis=1)
for i in range(len(students)) :
       print(students[i],"=" ,student_average[i])

Akash = 75.4
Riya = 76.8
Kajal = 66.0
Priya = 66.6
Rahul = 90.6
Mayank = 64.6


Subject-wise average helps to evaluate overall class strength and weekness

In [140]:
subject_average = np.mean(marks,axis=0)
for i in range(len(subjects)):
      print(subjects[i],"=",subject_average[i])

Maths = 71.0
Science = 89.5
English = 61.0
Hindi = 59.166666666666664
Social science = 86.0


max and min marks of student in subjects

In [97]:
marks

array([[90, 87, 67, 46, 87],
       [98, 78, 33, 87, 88],
       [78, 92, 44, 23, 93],
       [29, 99, 66, 59, 80],
       [92, 87, 93, 95, 86],
       [39, 94, 63, 45, 82]])

In [148]:
max_marks = np.max(marks,axis=1)
for i in range(len(students)):
         print(students[i],"=",max_marks[i])

Akash = 90
Riya = 98
Kajal = 93
Priya = 99
Rahul = 95
Mayank = 94


In [143]:
min_marks = np.min(marks,axis=1)
for i in range(len(students)):
    print(students[i],"=",min_marks[i])

Akash = 46
Riya = 33
Kajal = 23
Priya = 29
Rahul = 86
Mayank = 39


max and min marks of subject each student

In [152]:
max_marks_subject = np.max(marks,axis=0)
for i in range(len(subjects)):
         print(subjects[i],"=",max_marks_subject[i])

Maths = 98
Science = 99
English = 93
Hindi = 95
Social science = 93


In [154]:
min_marks_subject = np.min(marks, axis=0)
for i in range(len(subjects)):
    print(subjects[i],"=", min_marks_subject[i])

Maths = 29
Science = 78
English = 33
Hindi = 23
Social science = 80


pass / fail

In [102]:
marks

array([[90, 87, 67, 46, 87],
       [98, 78, 33, 87, 88],
       [78, 92, 44, 23, 93],
       [29, 99, 66, 59, 80],
       [92, 87, 93, 95, 86],
       [39, 94, 63, 45, 82]])

In [14]:
fail=np.where(marks<50)
for i in range(len(fail[0])):
    print(students[fail[0][i]],"in",subjects[fail[1][i]],"with marks",marks[fail[0][i],fail[1][i]])

Akash in Hindi with marks 46
Riya in English with marks 33
Kajal in English with marks 44
Kajal in Hindi with marks 23
Priya in Maths with marks 29
Mayank in Maths with marks 39
Mayank in Hindi with marks 45


Top performer

In [125]:
marks

array([[90, 87, 67, 46, 87],
       [98, 78, 33, 87, 88],
       [78, 92, 44, 23, 93],
       [29, 99, 66, 59, 80],
       [92, 87, 93, 95, 86],
       [39, 94, 63, 45, 82]])

In [16]:
total = np.sum(marks,axis=1)
for i in range(len(students)):
     print(students[i],"total marks of all subjects",total[i])

Akash total marks of all subjects 377
Riya total marks of all subjects 384
Kajal total marks of all subjects 330
Priya total marks of all subjects 333
Rahul total marks of all subjects 453
Mayank total marks of all subjects 323


In [29]:
topper = np.argmax(total)
print("Topper:", students[topper],"with",total[topper],"marks")

Topper: Rahul with 453 marks
